This is makeindex, version 2.16 [MiKTeX 23.5].
Scanning style file ./Report.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Report.acn....done (37 entries accepted, 0 rejected).
Sorting entries....done (214 comparisons).
Generating output file Report.acr....done (38 lines written, 0 warnings).
Output written in Report.acr.
Transcript written in Report.alg.
